---
# Logic to move existing content to the bucket:
#
# 1. Create a temporary directory on the host
# 2. Mount the bucket on there. This step also acts as a validation of
#    the ability to mount the bucket. # FIXME how do we handle failures?
# 3. Recursively copy the content below the mount point to the temporary directory.
# 4. Unmount the temporary directory
# 5. Move the content below the mount point to /tmp (or delete it?)

- name: Ensure we have a temporary directory
  ansible.builtin.tempfile:
    state: directory
    suffix: temp
  register: temp_dir

- name: Ensure bucket/prefix is mounted on temporary mount point
  ansible.posix.mount:
    path: "{{ temp_dir.path }}"
    src: "{{ _bucket }}:{{ mount.s3_prefix | ensure_leading_slash }}"
    fstype: fuse.s3fs
    opts: "{{ s3fs_flags | union(s3fs_auth_flags) | sort | join(',') }}"
    state: mounted
  register: tmpmount

# - debug: var=_find_check.files

- name: Set fact for unique directory paths sorted by depth
  ansible.builtin.set_fact:
    unique_dirs: >-
      {{
        _find_check.files
        | selectattr('isdir')
        | sort(attribute='path')
      }}

- name: Create required directory structure
  ansible.builtin.file:
    path: "{{ temp_dir.path }}/{{ item.path | relpath(mount.mount_point) }}"
    state: directory
    owner: "{{ item.pw_name if (item.pw_name | default('') | length > 0) else item.uid }}"
    group: "{{ item.gr_name if (item.gr_name | default('') | length > 0) else item.gid }}"
    mode: "{{ item.mode }}"
  loop: "{{ unique_dirs }}"
  loop_control:
    label: >-
      {{ item.path | relpath(mount.mount_point) }},
      type: directory,
      owner: {{ item.pw_name if (item.pw_name | default('') | length > 0) else item.uid }},
      group: {{ item.gr_name if (item.gr_name | default('') | length > 0) else item.gid }}

# cp will copy all file types (links, devices, fifo, etc)
- name: Copy items retaining attributes and special file types  # noqa no-changed-when
  ansible.builtin.command:
    cmd: >-
      cp -a --no-dereference
      {{ item.path | quote }}
      {{ (temp_dir.path ~ '/' ~ (item.path | relpath(mount.mount_point))) | quote }}
  loop: "{{ _find_check.files | rejectattr('isdir') }}"
  loop_control:
    label: >-
      {{ item.path | relpath(mount.mount_point) }},
      size: {{ (item.size / 1024) | round(1) }}kB,
      type: {{ 'symlink' if item.islnk else ('regular' if item.isreg else ('fifo' if item.isfifo else ('char_dev' if item.ischr else ('block_dev' if item.isblk else 'socket')))) }},
      owner: {{ item.pw_name if (item.pw_name | default('') | length > 0) else item.uid }},
      group: {{ item.gr_name if (item.gr_name | default('') | length > 0) else item.gid }}

- name: Verify that all content is correctly copied  # noqa no-changed-when command-instead-of-module
  ansible.builtin.command:
    cmd: >
      rsync
      --dry-run
      --archive
      --checksum
      --itemize-changes
      --omit-dir-times
      {{ mount.mount_point | ensure_trailing_slash | quote }}
      {{ temp_dir.path | ensure_trailing_slash | quote }}
  register: verify_copy

- name: Ensure temporary mount point is unmounted
  ansible.posix.mount:
    path: "{{ temp_dir.path }}"
    src: "{{ _bucket }}:{{ mount.s3_prefix | ensure_leading_slash }}"
    fstype: fuse.s3fs
    opts: "{{ s3fs_flags | union(s3fs_auth_flags) | sort | join(',') }}"
    state: absent
  register: tmpumount
  when: not verify_copy.failed

- name: Ensure content below mount point is removed  # noqa no-changed-when
  ansible.builtin.command:
    cmd: >
      find {{ mount.mount_point | quote }} -mindepth 1 -delete
  when: not verify_copy.failed

# - debug: var=tmpmount
# - debug: var=rcp
# - debug: var=tmpumount
