---
- name: Ensure required packages are installed
  ansible.builtin.apt:
    name:
      - s3fs
      - python3-boto3
      - python3-botocore
  become: true

# TODO safety/sanity checks here, before we start doing work

- name: Ensure mounts are available
  ansible.builtin.include_tasks:
    file: mount.yml
  loop: "{{ s3fs_mounts }}"
  loop_control:
    loop_var: mount
