---
- name: Ensure required packages are installed
  ansible.builtin.apt:
    name:
      - s3fs
      - rsync
  become: true

# TODO safety/sanity checks here, before we start doing work

- name: Ensure mounts are available
  environment:
    AWS_ACCESS_KEY_ID: "{{ mount.access_key | default(s3fs_access_key, true) | default(omit, true) }}"
    AWS_SECRET_ACCESS_KEY: "{{ mount.secret_key | default(s3fs_secret_key, true) | default(omit, true) }}"
    AWS_REGION: "{{ mount.region | default(s3fs_region, true) | default(omit, true) }}"
    AWS_DEFAULT_REGION: "{{ mount.region | default(s3fs_region, true) | default(omit, true) }}"
  block:
    - name: Include mount tasks
      ansible.builtin.include_tasks:
        file: mount.yml
      loop: "{{ s3fs_mounts }}"
      loop_control:
        loop_var: mount
