---
# TODO: verify all required options are set
# -> ensure s3_prefix has one trailing slash
# -> ensure s3_prefix does not have a leading slash

- name: Stat mount_point
  ansible.builtin.stat:
    path: "{{ mount.mount_point }}"
  register: _mount_point

# TODO verify S3 authorisation if static credentials are set
# - name: Verify S3 authorisation before mounting
#   amazon.aws.s3_object_info:
#     bucket: "my-s3-bucket"
#     aws_access_key: "{{ s3_access_key }}"
#     aws_secret_key: "{{ s3_secret_key }}"
#   delegate_to: localhost

# If the above works, then ensure that the credentials are available as
# a single line in the system wide file /etc/passwd-s3fs:
# bucket-alpha:AKIAIOSFODNN7EXAMPLE:wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
#

- name: Safety check
  ansible.builtin.assert:
    that:
      - _mount_point.stat.exists
      - _mount_point.stat.isdir
    fail_msg: >-
      For mount '{{ mount.name }}', mount point '{{ mount.mount_point }}' does not exist or is not a directory.
    quiet: true

# After this point the mount_point exists and is a directory

- name: Check if something is already mounted on mount point
  ansible.builtin.command:
    cmd: findmnt --mountpoint {{ mount.mount_point | quote }} --json
  register: _findmnt
  changed_when: false
  failed_when: false

- name: Set facts
  ansible.builtin.set_fact:
    mount_point_is_mounted: "{{ _findmnt.rc == 0 }}"
    _bucket: "{{ mount.bucket | default(s3fs_bucket) }}"

- name: Find content below mount point
  ansible.builtin.find:
    paths:
      - "{{ mount.mount_point }}"
    file_type: any
    recurse: true
  register: _find_check
  changed_when: false
  failed_when: false
  when: not mount_point_is_mounted

- name: Prompt user for copy confirmation
  ansible.builtin.pause:
    prompt: |
      WARNING for mount '{{ mount.name }}', the mount point {{ mount.mount_point }} is not empty:

      {{ _find_check | to_tree(mount.mount_point) }}

      Should we recursively copy this content to the bucket? [y/N]
  register: user_input_response
  when: (_find_check.matched | default(0) > 0)

- name: Set copy confirmation flag
  ansible.builtin.set_fact:
    should_copy_content: "{{ (user_input_response.user_input | default('') | lower) in ['y', 'yes'] | default(false) }}"

- name: Check 0-byte directory marker existance
  amazon.aws.s3_object_info:
    bucket_name: "{{ _bucket }}"
    prefix: "{{ mount.s3_prefix }}"
    max_keys: 1
  delegate_to: localhost
  become: false
  register: zbm

- name: Fetch 0-byte directory marker info
  amazon.aws.s3_object_info:
    bucket_name: "{{ _bucket }}"
    object_name: "{{ mount.s3_prefix }}"
    max_keys: 1
  delegate_to: localhost
  become: false
  when: zbm.s3_keys|length == 1
  register: zbmi

- name: Set metadata
  ansible.builtin.set_fact:
    required_metadata:
      uid: "{{ _mount_point.stat.uid | string }}"
      gid: "{{ _mount_point.stat.gid | string }}"
      mode: "0{{ _mount_point.stat.mode | string }}"
    current_metadata: "{{ zbmi | json_query('object_info[0].object_data.metadata') | default({}, true) }}"

- name: Set update flag
  ansible.builtin.set_fact:
    metadata_needs_updating: "{{ required_metadata.items() | difference(current_metadata.items()) | length > 0 }}"

- name: Ensure 0 byte marker exists
  amazon.aws.s3_object:
    bucket: "{{ _bucket }}"
    object: "{{ mount.s3_prefix }}"
    region: "{{ aws_region }}"
    mode: put
    content: ""
    overwrite: always
    metadata: "{{ required_metadata }}"
    headers:
      Content-Type: "application/x-directory"
  delegate_to: localhost
  become: false
  when: (zbm.s3_keys | length == 0) or metadata_needs_updating

- name: Ensure dependent systemd services are stopped
  ansible.builtin.systemd_service:
    name: "{{ service }}"
    state: stopped
  loop: "{{ mount.services | default([]) }}"
  loop_control:
    loop_var: service

- name: Ensure existing content is copied to bucket
  ansible.builtin.include_tasks:
    file: copy_content_to_bucket.yml
  when: should_copy_content

- name: Ensure bucket/prefix is mounted
  ansible.posix.mount:
    path: "{{ mount.mount_point }}"
    # This does need a slash before the prefix. Because we have made sure there
    # is no leading slash, we can hard code one here.
    src: "{{ _bucket }}:/{{ mount.s3_prefix }}"
    fstype: fuse.s3fs
    opts: "{{ s3fs_flags | sort | join(',') }}"
    state: mounted

- name: Ensure dependent systemd services are started again
  ansible.builtin.systemd_service:
    name: "{{ service }}"
    state: started
  loop: "{{ mount.services | default([]) }}"
  loop_control:
    loop_var: service
